### ISSUE TITLE
Add actual DNS records for `mjlife.se` domain

### ISSUE THREAD

**Issue by mblomdahl** [vtepliuk/mjlife.se#4]
The use of `vagrant.mjlife.se` DNS name currently (and undocumentedly) relies on hacking the `/etc/hosts` file... Not so nice. Having control of the domain name will be required anyway, so let's add the "private IP hack" there instead. More neat!! ✔️

**Comment by vtepliuk** [comment]
Done and done. :)

```plain
EMB2:~ vtepliuk$ nslookup vagrant.mjlife.se ns2.loopia.se
Server:		ns2.loopia.se
Address:	93.188.0.21#53

Name:	vagrant.mjlife.se
Address: 10.187.57.250

EMB2:~ vtepliuk$ 
```
